-- GENERATED by tools/gen-achievements.py -- do not edit by hand.
--
-- Pandaren in the achievements that name races one by one, and a realm first
-- per faction. The client patch carries the same rows (Achievement.dbc,
-- Achievement_Criteria.dbc); the server decides what completes them.
--
--   1431 / 1432  Realm First! Level 80 Pandaren, Alliance / Horde
--   246 / 1005   Know Thy Enemy: a killing blow on a pandaren of the other faction
--   291          Check Your Head
--   2422         Shake Your Bunny-Maker (female, level 18+)
--
-- Check Your Head and Shake Your Bunny-Maker check the target's race with a
-- data row that takes one race. Pandaren are two race ids, so their criteria
-- use the script achievement_pandaren_target (src/), which takes 20 or 21.
--
-- All four existing achievements require every criterion (minimum criteria
-- 0), so a new criterion is required without touching the achievement. A
-- player who has already completed one keeps it.

DELETE FROM `achievement_dbc` WHERE `ID` IN (1431, 1432);
INSERT INTO `achievement_dbc` (`ID`, `Faction`, `Instance_Id`, `Supercedes`, `Title_Lang_enUS`, `Title_Lang_enGB`, `Title_Lang_koKR`, `Title_Lang_frFR`, `Title_Lang_deDE`, `Title_Lang_enCN`, `Title_Lang_zhCN`, `Title_Lang_enTW`, `Title_Lang_zhTW`, `Title_Lang_esES`, `Title_Lang_esMX`, `Title_Lang_ruRU`, `Title_Lang_ptPT`, `Title_Lang_ptBR`, `Title_Lang_itIT`, `Title_Lang_Unk`, `Title_Lang_Mask`, `Description_Lang_enUS`, `Description_Lang_enGB`, `Description_Lang_koKR`, `Description_Lang_frFR`, `Description_Lang_deDE`, `Description_Lang_enCN`, `Description_Lang_zhCN`, `Description_Lang_enTW`, `Description_Lang_zhTW`, `Description_Lang_esES`, `Description_Lang_esMX`, `Description_Lang_ruRU`, `Description_Lang_ptPT`, `Description_Lang_ptBR`, `Description_Lang_itIT`, `Description_Lang_Unk`, `Description_Lang_Mask`, `Category`, `Points`, `Ui_Order`, `Flags`, `IconID`, `Reward_Lang_enUS`, `Reward_Lang_enGB`, `Reward_Lang_koKR`, `Reward_Lang_frFR`, `Reward_Lang_deDE`, `Reward_Lang_enCN`, `Reward_Lang_zhCN`, `Reward_Lang_enTW`, `Reward_Lang_zhTW`, `Reward_Lang_esES`, `Reward_Lang_esMX`, `Reward_Lang_ruRU`, `Reward_Lang_ptPT`, `Reward_Lang_ptBR`, `Reward_Lang_itIT`, `Reward_Lang_Unk`, `Reward_Lang_Mask`, `Minimum_Criteria`, `Shares_Criteria`) VALUES
  (1431, 1, -1, 0, 'Realm First! Level 80 Pandaren', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'First pandaren of the Alliance on the realm to achieve level 80.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 81, 0, 163, 256, 4400, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712174, 0, 0),
  (1432, 0, -1, 0, 'Realm First! Level 80 Pandaren', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'First pandaren of the Horde on the realm to achieve level 80.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 81, 0, 164, 256, 4400, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712174, 0, 0);

DELETE FROM `achievement_criteria_dbc` WHERE `ID` IN (13501, 13502, 13503, 13504, 13505, 13506);
INSERT INTO `achievement_criteria_dbc` (`ID`, `Achievement_Id`, `Type`, `Asset_Id`, `Quantity`, `Start_Event`, `Start_Asset`, `Fail_Event`, `Fail_Asset`, `Description_Lang_enUS`, `Description_Lang_enGB`, `Description_Lang_koKR`, `Description_Lang_frFR`, `Description_Lang_deDE`, `Description_Lang_enCN`, `Description_Lang_zhCN`, `Description_Lang_enTW`, `Description_Lang_zhTW`, `Description_Lang_esES`, `Description_Lang_esMX`, `Description_Lang_ruRU`, `Description_Lang_ptPT`, `Description_Lang_ptBR`, `Description_Lang_itIT`, `Description_Lang_Unk`, `Description_Lang_Mask`, `Flags`, `Timer_Start_Event`, `Timer_Asset_Id`, `Timer_Time`, `Ui_Order`) VALUES
  (13501, 1431, 5, 0, 80, 0, 0, 0, 0, 'Level to 80', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 2, 0, 0, 0, 1),
  (13502, 1432, 5, 0, 80, 0, 0, 0, 0, 'Level to 80', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 2, 0, 0, 0, 1),
  (13503, 246, 53, 21, 1, 0, 0, 0, 0, 'Pandaren', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 0, 0, 0, 0, 7),
  (13504, 1005, 53, 20, 1, 0, 0, 0, 0, 'Pandaren', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 0, 0, 0, 0, 7),
  (13505, 291, 110, 44212, 1, 0, 0, 0, 0, 'Pandaren', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 0, 0, 0, 0, 13),
  (13506, 2422, 110, 61815, 1, 0, 0, 0, 0, 'Pandaren', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 0, 0, 0, 0, 13);

DELETE FROM `achievement_criteria_data` WHERE `criteria_id` IN (13501, 13502, 13503, 13504, 13505, 13506);
INSERT INTO `achievement_criteria_data` (`criteria_id`, `type`, `value1`, `value2`, `ScriptName`) VALUES
  (13501, 21, 0, 20, ''),
  (13502, 21, 0, 21, ''),
  (13505, 11, 0, 0, 'achievement_pandaren_target'),
  (13506, 9, 18, 0, ''),
  (13506, 10, 1, 0, ''),
  (13506, 11, 0, 0, 'achievement_pandaren_target');

-- Check, after a restart: no `achievement_criteria_data` or "achievement"
-- errors for these IDs in Server.log, and in game the achievements list the
-- Pandaren criterion.
