-- GENERATED by tools/gen-race-skill-masks.py -- do not edit by hand.
--
-- The race masks zz_pandaren_04 cannot reach, because they live in the .dbc
-- FILE and not in the override table. An UPDATE only hits rows someone has
-- already overridden; the rest must be INSERTed with the value they have.
--
-- Without this file a pandaren learns none of its four racials, cannot
-- speak its faction language, cannot learn a mount and has no shaman
-- talent trees. All silently: LearnDefaultSkill returns without logging,
-- and _LoadSkills then deletes any skill without a SkillRaceClassInfo row.
--
-- The rule mirrors the source race: night elf for race 20 (draenei for its
-- shamans and mages, which night elves cannot be), troll for race 21.
-- Masks naming exactly one race are left alone: that race's own racial and
-- language line, and mirroring it would give Alliance pandaren Shadowmeld
-- and Darnassian.
--
-- The rows are generated from an unmodified 3.3.5a client. If your server's DBC files
-- or override tables differ (another race module that ships its own DBC
-- files), regenerate this file from yours.
--
-- A row already in the table (another module overrode it and ran first) is
-- not replaced: ON DUPLICATE KEY UPDATE applies the same rule to the mask
-- it already has. That also makes a rerun a no-op.

-- ------------------------------------------------------------------------
-- SkillRaceClassInfo: the gate for every skill
-- 155 rows.

INSERT INTO `skillraceclassinfo_dbc` (`ID`, `SkillID`, `RaceMask`, `ClassMask`, `Flags`, `MinLevel`, `SkillTierID`, `SkillCostIndex`) VALUES
  (21, 293, 1574911, 3, 128, 40, 0, 0),   -- Plate Mail
  (24, 272, 1050623, 1024, 1168, 10, 0, 0),
  (26, 247, 1050623, 1024, 1168, 20, 0, 0),
  (27, 356, 1574911, 1535, 128, 0, 23, 0),   -- Fishing
  (28, 182, 1574911, 1535, 160, 0, 2, 0),   -- Herbalism
  (29, 186, 1574911, 1535, 160, 0, 2, 0),   -- Mining
  (30, 393, 1574911, 1535, 160, 0, 161, 0),   -- Skinning
  (34, 273, 1574911, 4, 128, 0, 0, 0),
  (35, 262, 1574911, 4, 128, 0, 0, 0),
  (36, 263, 1574911, 4, 128, 0, 0, 0),
  (37, 264, 1574911, 4, 128, 0, 0, 0),
  (38, 260, 1574911, 4, 128, 0, 0, 0),
  (40, 98, 525389, 1535, 128, 0, 0, 0),   -- Language: Common
  (41, 98, 1049250, 1503, 160, 0, 21, 0),   -- Language: Common
  (43, 113, 1574903, 1503, 160, 0, 21, 0),   -- Language: Darnassian
  (45, 111, 1574907, 1503, 160, 0, 21, 0),   -- Language: Dwarven
  (47, 313, 1574847, 1503, 160, 0, 21, 0),   -- Language: Gnomish
  (48, 109, 1049266, 1535, 128, 0, 0, 0),   -- Language: Orcish
  (49, 109, 525389, 1503, 160, 0, 21, 0),   -- Language: Orcish
  (51, 115, 1574879, 1503, 160, 0, 21, 0),   -- Language: Taurahe
  (53, 315, 526207, 1503, 160, 0, 21, 0),   -- Language: Troll
  (54, 130, 1574911, 128, 1168, 4, 0, 0),
  (59, 96, 1050623, 1024, 1168, 0, 0, 0),
  (62, 268, 1050623, 2, 1170, 0, 0, 0),
  (64, 269, 1050623, 2, 1168, 0, 0, 0),
  (65, 198, 1050623, 2, 1168, 0, 0, 0),
  (66, 246, 1050623, 2, 1168, 0, 0, 0),
  (73, 254, 1574911, 8, 1168, 10, 0, 0),
  (76, 241, 1574911, 8, 128, 40, 0, 0),
  (79, 238, 1574911, 8, 1168, 4, 0, 0),
  (81, 239, 1574911, 8, 1168, 0, 0, 0),
  (83, 252, 1574911, 9, 128, 0, 0, 0),
  (84, 139, 1574911, 1535, 160, 0, 21, 0),   -- Language: Demon Tongue
  (85, 138, 1574911, 1535, 128, 0, 0, 0),   -- Language: Draconic
  (88, 141, 1574911, 1535, 160, 0, 21, 0),   -- Language: Old Tongue
  (91, 137, 1574399, 1503, 160, 0, 21, 0),   -- Language: Thalassian
  (93, 140, 1574911, 1535, 128, 0, 0, 0),   -- Language: Titan
  (96, 375, 1835007, 64, 1040, 0, 0, 0),   -- Elemental Combat
  (97, 199, 1574911, 64, 1168, 0, 0, 0),
  (98, 374, 1835007, 64, 1040, 0, 0, 0),   -- Restoration
  (104, 353, 1050623, 256, 1170, 0, 0, 0),
  (105, 120, 1050623, 256, 1170, 0, 0, 0),
  (106, 245, 1574911, 1, 1168, 0, 0, 0),
  (108, 255, 1574911, 1, 1168, 0, 0, 0),
  (111, 244, 1574911, 1, 1168, 0, 0, 0),
  (112, 243, 1574911, 1, 1170, 0, 0, 0),
  (113, 258, 1574911, 1, 1168, 10, 0, 0),
  (117, 44, 1048742, 4, 128, 0, 0, 0),   -- Axes
  (122, 172, 1212415, 2, 128, 0, 0, 0),   -- Two-Handed Axes
  (123, 160, 1310719, 2, 128, 0, 0, 0),   -- Two-Handed Maces
  (125, 55, 1835007, 4, 128, 0, 0, 0),   -- Two-Handed Swords
  (126, 45, 1573514, 4, 128, 0, 0, 0),   -- Bows
  (127, 45, 1605631, 13, 128, 0, 0, 0),   -- Bows
  (128, 226, 1605631, 9, 128, 0, 0, 0),   -- Crossbows
  (129, 173, 1605631, 264, 128, 0, 0, 0),   -- Daggers
  (131, 118, 1605631, 8, 146, 1, 0, 0),   -- Dual Wield
  (132, 118, 1605631, 5, 146, 20, 0, 0),   -- Dual Wield
  (134, 46, 1605631, 9, 128, 0, 0, 0),   -- Guns
  (136, 229, 1605631, 1031, 128, 20, 0, 0),   -- Polearms
  (137, 227, 1574911, 1029, 128, 0, 0, 0),
  (138, 136, 1605631, 1488, 128, 0, 0, 0),   -- Staves
  (139, 136, 1605631, 5, 128, 0, 0, 0),   -- Staves
  (140, 43, 525403, 1, 128, 0, 0, 0),   -- Swords
  (145, 413, 1574911, 68, 128, 40, 0, 0),   -- Mail
  (146, 413, 1574911, 35, 128, 0, 0, 0),   -- Mail
  (147, 414, 1574911, 1135, 128, 0, 0, 0),   -- Leather
  (148, 415, 1574911, 1535, 128, 0, 0, 0),   -- Cloth
  (149, 242, 1574911, 8, 1168, 16, 0, 0),
  (151, 416, 1574911, 1, 192, 0, 0, 0),
  (155, 416, 1050623, 2, 192, 0, 0, 1),
  (158, 416, 1574911, 1088, 192, 0, 0, 1),
  (159, 416, 1574911, 12, 192, 0, 0, 1),
  (175, 418, 1574911, 1, 384, 0, 0, 0),
  (178, 418, 1050623, 2, 384, 0, 0, 0),
  (183, 418, 1574911, 1284, 384, 0, 0, 1),
  (186, 418, 1574911, 144, 384, 0, 0, 1),
  (189, 419, 1574911, 12, 640, 0, 0, 2),
  (191, 419, 1050623, 1024, 640, 0, 0, 1),
  (193, 419, 1574911, 144, 640, 0, 0, 0),
  (198, 419, 1050623, 2, 640, 0, 0, 1),
  (200, 419, 1574911, 1, 640, 0, 0, 2),
  (203, 420, 1574911, 13, 1152, 0, 0, 2),
  (204, 420, 1050623, 1026, 1152, 0, 0, 1),
  (205, 420, 1574911, 272, 1152, 0, 0, 0),
  (241, 171, 1574911, 1535, 160, 0, 41, 0),   -- Alchemy
  (243, 164, 1574911, 1535, 160, 0, 41, 0),   -- Blacksmithing
  (244, 202, 1574911, 1535, 160, 0, 41, 0),   -- Engineering
  (246, 433, 1574911, 67, 128, 0, 0, 0),   -- Shield
  (265, 419, 1050623, 256, 640, 0, 0, 0),
  (266, 419, 1574911, 64, 640, 0, 0, 1),
  (268, 420, 1574911, 128, 1152, 0, 0, 0),
  (269, 420, 1574911, 64, 1152, 0, 0, 1),
  (270, 418, 1574911, 72, 384, 0, 0, 1),
  (271, 416, 1574911, 400, 192, 0, 0, 2),
  (272, 453, 1574911, 3, 128, 0, 0, 0),
  (281, 333, 1574911, 1535, 160, 0, 62, 0),   -- Enchanting
  (282, 185, 1574911, 1535, 128, 0, 61, 0),   -- Cooking
  (284, 197, 1574911, 1535, 160, 0, 62, 0),   -- Tailoring
  (323, 173, 1605631, 208, 128, 0, 0, 0),   -- Daggers
  (328, 43, 1575935, 4, 128, 0, 0, 0),   -- Swords
  (330, 473, 1576959, 1101, 130, 0, 0, 0),   -- Fist Weapons
  (403, 515, 1574911, 1503, 128, 0, 0, 0),
  (441, 148, 1573086, 1535, 1170, 0, 182, 0),   -- Horse Riding
  (442, 152, 1573083, 1535, 1170, 0, 182, 0),   -- Ram Riding
  (443, 149, 1573373, 1535, 1170, 0, 182, 0),   -- Wolf Riding
  (446, 533, 524383, 1503, 1170, 0, 182, 0),   -- Raptor Riding
  (464, 554, 1573071, 1535, 1170, 0, 182, 0),   -- Undead Horsemanship
  (481, 150, 1048791, 1535, 1170, 0, 182, 0),   -- Tiger Riding
  (622, 172, 1574393, 1, 128, 0, 0, 0),   -- Two-Handed Axes
  (625, 160, 1834975, 1, 128, 0, 0, 0),   -- Two-Handed Maces
  (626, 55, 1736703, 1, 128, 0, 0, 0),   -- Two-Handed Swords
  (628, 44, 525832, 4, 128, 0, 0, 0),   -- Axes
  (629, 44, 1048743, 1, 128, 0, 0, 0),   -- Axes
  (630, 44, 525400, 1, 128, 0, 0, 0),   -- Axes
  (631, 173, 524808, 4, 128, 0, 0, 0),   -- Daggers
  (632, 173, 1049766, 4, 128, 0, 0, 0),   -- Daggers
  (633, 173, 1573080, 1, 128, 0, 0, 0),   -- Daggers
  (635, 46, 1574538, 4, 128, 0, 0, 0),   -- Guns
  (636, 54, 525421, 1, 128, 0, 0, 0),   -- Maces
  (637, 54, 1049234, 1, 128, 0, 0, 0),   -- Maces
  (638, 43, 1048740, 1, 128, 0, 0, 0),   -- Swords
  (640, 176, 786303, 1, 128, 0, 0, 0),   -- Thrown
  (701, 172, 1736703, 64, 128, 0, 0, 0),   -- Two-Handed Axes
  (742, 673, 1574895, 1503, 160, 0, 21, 0),   -- Language: Gutterspeak
  (781, 713, 1573119, 1535, 1170, 0, 181, 0),   -- Kodo Riding
  (865, 142, 1574911, 1535, 0, 0, 0, 0),   -- Survival
  (866, 755, 1574911, 1535, 160, 0, 41, 0),   -- Jewelcrafting
  (872, 43, 1605631, 8, 128, 0, 0, 0),   -- Swords
  (876, 759, 1573887, -1, 0, 0, 21, 0),   -- Language: Draenei
  (879, 226, 1604607, 4, 128, 0, 0, 0),   -- Crossbows
  (881, 43, 1605631, 384, 128, 0, 0, 0),   -- Swords
  (883, 118, 1605631, 64, 402, 0, 0, 0),   -- Dual Wield
  (888, 54, 1310207, 2, 128, 0, 0, 0),   -- Maces
  (892, 769, 1605631, 1535, 1040, 0, 0, 0),   -- Internal
  (897, 771, 1310719, 32, 1040, 0, 0, 0),   -- Frost
  (898, 55, 1310719, 32, 128, 0, 0, 0),   -- Two-Handed Swords
  (899, 165, 1574911, 1535, 160, 0, 41, 0),   -- Leatherworking
  (900, 773, 1835007, 1535, 160, 0, 41, 0),   -- Inscription
  (901, 55, 1310207, 2, 128, 0, 0, 0),   -- Two-Handed Swords
  (906, 293, 1310719, 32, 128, 0, 0, 0),   -- Plate Mail
  (907, 172, 1572863, 32, 128, 0, 0, 0),   -- Two-Handed Axes
  (908, 160, 1310719, 32, 128, 0, 0, 0),   -- Two-Handed Maces
  (910, 43, 1310719, 32, 128, 0, 0, 0),   -- Swords
  (912, 44, 1310719, 32, 128, 0, 0, 0),   -- Axes
  (913, 118, 1310719, 32, 146, 0, 0, 0),   -- Dual Wield
  (914, 54, 1310719, 32, 128, 0, 0, 0),   -- Maces
  (915, 229, 1310719, 32, 128, 0, 0, 0),   -- Polearms
  (916, 95, 1572863, 32, 640, 0, 0, 0),   -- Defense
  (922, 162, 1310719, 32, 128, 0, 0, 0),   -- Unarmed
  (934, 762, 1572863, 32, 144, 0, 223, 0),   -- Riding
  (936, 776, 1310719, 32, 128, 0, 0, 0),   -- Runeforging
  (938, 777, 2097151, 1535, 2, 0, 0, 0),   -- Mounts
  (939, 778, 2097151, 1535, 2, 0, 0, 0),   -- Companions
  (940, 205, 2097151, 128, 2048, 0, 0, 0),   -- Pet - Succubus
  (970, 172, 1736703, 4, 128, 0, 0, 0)   -- Two-Handed Axes
ON DUPLICATE KEY UPDATE `RaceMask` = `RaceMask` | IF(`RaceMask` > 0 AND BIT_COUNT(`RaceMask` & 4095) > 1 AND ((`RaceMask` & 8) <> 0 AND (`ClassMask` = 0 OR (`ClassMask` & 29) <> 0) OR (`RaceMask` & 1024) <> 0 AND (`ClassMask` & 192) <> 0), 524288, 0) | IF(`RaceMask` > 0 AND BIT_COUNT(`RaceMask` & 4095) > 1 AND (`RaceMask` & 128) <> 0, 1048576, 0);

-- ------------------------------------------------------------------------
-- SkillLineAbility: which spells a skill line hands out
-- 35 rows.

INSERT INTO `skilllineability_dbc` (`ID`, `SkillLine`, `Spell`, `RaceMask`, `ClassMask`, `ExcludeRace`, `ExcludeClass`, `MinSkillLineRank`, `SupercededBySpell`, `AcquireMethod`, `TrivialSkillLineRankHigh`, `TrivialSkillLineRankLow`, `CharacterPoints_1`, `CharacterPoints_2`) VALUES
  (590, 98, 668, 525389, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0),   -- Language: Common
  (592, 109, 669, 1049266, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0),   -- Language: Orcish
  (3269, 237, 3565, 525389, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (3270, 237, 3562, 525389, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (3271, 237, 3567, 1049266, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (3272, 237, 3561, 525389, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (3273, 237, 3566, 1049266, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (3274, 237, 3563, 1049266, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (5989, 237, 11419, 525389, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (5990, 237, 11416, 525389, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (5991, 237, 11417, 1049266, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (5992, 237, 10059, 525389, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (5993, 237, 11420, 1049266, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (5994, 237, 11418, 1049266, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (13151, 373, 2825, 1048738, 64, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Enhancement
  (14815, 237, 32271, 525389, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (14816, 237, 32272, 1049266, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (14817, 237, 32266, 525389, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (14818, 237, 32267, 1049266, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (15040, 237, 33690, 525389, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (15041, 237, 33691, 525389, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (15606, 237, 35715, 1049266, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (15607, 237, 35717, 1049266, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (16999, 237, 49359, 525389, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (17000, 237, 49358, 1049266, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (17003, 237, 49361, 1049266, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (17004, 237, 49360, 525389, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Arcane
  (20110, 777, 55531, 1049266, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Mounts
  (20283, 777, 60424, 525389, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0),   -- Mounts
  (20289, 202, 60867, 525389, 0, 0, 0, 1, 0, 0, 490, 480, 0, 0),   -- Engineering
  (20290, 202, 60866, 1049266, 0, 0, 0, 1, 0, 0, 490, 480, 0, 0),   -- Engineering
  (20867, 183, 63645, 1576959, 1535, 0, 0, 1, 0, 2, 0, 0, 0, 0),   -- GENERIC (DND)
  (20868, 183, 63644, 1576959, 1535, 0, 0, 1, 0, 2, 0, 0, 0, 0),   -- GENERIC (DND)
  (21723, 253, 75460, 1574655, 8, 0, 0, 1, 0, 2, 0, 0, 0, 0),   -- Assassination
  (21724, 375, 75461, 1574655, 64, 0, 0, 1, 0, 2, 0, 0, 0, 0)   -- Elemental Combat
ON DUPLICATE KEY UPDATE `RaceMask` = `RaceMask` | IF(`RaceMask` > 0 AND BIT_COUNT(`RaceMask` & 4095) > 1 AND ((`RaceMask` & 8) <> 0 AND (`ClassMask` = 0 OR (`ClassMask` & 29) <> 0) OR (`RaceMask` & 1024) <> 0 AND (`ClassMask` & 192) <> 0), 524288, 0) | IF(`RaceMask` > 0 AND BIT_COUNT(`RaceMask` & 4095) > 1 AND (`RaceMask` & 128) <> 0, 1048576, 0);

-- Check. Neither may return more than 0:
--
--   SELECT COUNT(*) FROM skillraceclassinfo_dbc
--    WHERE RaceMask > 0 AND (RaceMask & 8) <> 0
--      AND (ClassMask = 0 OR (ClassMask & 29) <> 0)
--      AND BIT_COUNT(RaceMask & 4095) > 1 AND (RaceMask & 524288) = 0;
--   SELECT COUNT(*) FROM skilllineability_dbc
--    WHERE RaceMask > 0 AND (RaceMask & 128) <> 0
--      AND BIT_COUNT(RaceMask & 4095) > 1 AND (RaceMask & 1048576) = 0;
--
-- And in game: create a pandaren and list its skills.
--   SELECT skill FROM acore_characters.character_skills WHERE guid = <new pandaren>;
-- Must contain 791 (racial line), 98 or 109 (language), 777 and 778.
