-- GENERATED by tools/gen-shared-sql.py from client/rows/ -- do not edit by hand.
--
-- Pandaren model and display rows, the same as the client patch's.
--
-- Pandaren do not exist in 3.3.5 at all, so both model and display are created
-- here. A free ID must be free in the DBC file AND in the override table:
-- CreatureModelData's IDs are sparse up to 7050 (3700 and 3701 are unused
-- gaps), CreatureDisplayInfo ends at 36446. DBCDatabaseLoader::Load fills gaps
-- and extends the index alike.
--
-- The file name must end in .mdx, not .m2: the client maps .mdx to .m2 on
-- lookup, and every existing race is written that way.
--
-- The collision box is read off the model's own collision box, the way the
-- stock races' rows agree with their models. A wrong CollisionHeight shows as
-- a character sunk into or floating above the ground, a wrong MountHeight as
-- a rider beside the mount.
--
-- ExtendedDisplayInfoID 0 is right for a PLAYER display: the texture is
-- composed from the player's own skin and hair. An NPC would need a baked
-- CreatureDisplayInfoExtra row, or it stands untextured.

DELETE FROM `creaturemodeldata_dbc` WHERE `ID` IN (3700, 3701);
DELETE FROM `creaturedisplayinfo_dbc` WHERE `ID` IN (39500, 39501);

INSERT INTO `creaturemodeldata_dbc` (`ID`, `Flags`, `ModelName`, `SizeClass`, `ModelScale`, `BloodID`, `FootprintTextureID`, `FootprintTextureLength`, `FootprintTextureWidth`, `FootprintParticleScale`, `FoleyMaterialID`, `FootstepShakeSize`, `DeathThudShakeSize`, `SoundID`, `CollisionWidth`, `CollisionHeight`, `MountHeight`, `GeoBoxMinX`, `GeoBoxMinY`, `GeoBoxMinZ`, `GeoBoxMaxX`, `GeoBoxMaxY`, `GeoBoxMaxZ`, `WorldEffectScale`, `AttachedEffectScale`, `MissileCollisionRadius`, `MissileCollisionPush`, `MissileCollisionRaise`) VALUES
  (3700, 4, 'Character\\Pandaren\\Male\\PandarenMale.mdx', 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.611111104, 2.03127789, 1.036183, -0.576729, -0.544345021, -0.000693999988, 0.368137002, 0.535902023, 2.12919998, 1, 1, 0, 0, 0),
  (3701, 4, 'Character\\Pandaren\\Female\\PandarenFemale.mdx', 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.611111104, 2.03127789, 1.00263703, -0.487307012, -0.359981, -0.00222299993, 0.275954992, 0.370420992, 1.92493498, 1, 1, 0, 0, 0);

INSERT INTO `creaturedisplayinfo_dbc` (`ID`, `ModelID`, `SoundID`, `ExtendedDisplayInfoID`, `CreatureModelScale`, `CreatureModelAlpha`, `TextureVariation_1`, `TextureVariation_2`, `TextureVariation_3`, `PortraitTextureName`, `BloodLevel`, `BloodID`, `NPCSoundID`, `ParticleColorID`, `CreatureGeosetData`, `ObjectEffectPackageID`) VALUES
  (39500, 3700, 0, 0, 1, 255, '', '', '', '', 0, 0, 0, 0, 0, 0),
  (39501, 3701, 0, 0, 1, 255, '', '', '', '', 0, 0, 0, 0, 0, 0);
