#!/usr/bin/env python3
"""Generate the faction_dbc rows that give pandaren their base reputation.

`ReputationMgr::GetBaseReputation()` walks FactionEntry::BaseRepRaceMask[0..3]
and returns BaseRepValue for the first slot matching the player's race mask;
falling off the end returns 0. Races 20 and 21 are outside every mask in
Faction.dbc, so without these rows a pandaren starts Neutral with everything,
its own capital included.

The rule mirrors the source race: wherever night elf is entitled, so is race 20;
wherever troll is, so is race 21. Testing for "all Alliance" would not work:
capitals cut their own race out into a separate slot with a higher value
(Ironforge is "Alliance minus dwarf", Darnassus "Alliance minus night elf"), so
an exact match would give pandaren no city reputation at all.

A DBC override replaces the whole row, so each faction is written in full,
names included (left out, the server's faction names go blank). The rows are
read from the server's Faction.dbc. For a row that is already in faction_dbc
(another module overrides that faction and ran first), the INSERT becomes an
UPDATE that only adds the pandaren bits to the masks already there.

    gen-faction-dbc.py --dbc <server dbc dir>/Faction.dbc --out <file.sql>

Run it against the Faction.dbc your server actually loads. The shipped SQL is
generated from an unmodified 3.3.5a (12340) client.
"""
import argparse
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dbc import DBC  # noqa: E402

BIT_NIGHTELF, BIT_TROLL = 1 << 3, 1 << 7
RACE_A, RACE_H = 1 << 19, 1 << 20    # races 20 and 21

NUMERIC = [
    'ID', 'ReputationIndex',
    'ReputationRaceMask_1', 'ReputationRaceMask_2', 'ReputationRaceMask_3', 'ReputationRaceMask_4',
    'ReputationClassMask_1', 'ReputationClassMask_2', 'ReputationClassMask_3', 'ReputationClassMask_4',
    'ReputationBase_1', 'ReputationBase_2', 'ReputationBase_3', 'ReputationBase_4',
    'ReputationFlags_1', 'ReputationFlags_2', 'ReputationFlags_3', 'ReputationFlags_4',
    'ParentFactionID', 'ParentFactionMod_1', 'ParentFactionMod_2',
    'ParentFactionCap_1', 'ParentFactionCap_2',
]
SIGNED = {1, 10, 11, 12, 13}          # ReputationIndex and the four base values
FLOATS = {19, 20}                     # ParentFactionMod_1/2
NAME0, DESC0, NFLAGS, DFLAGS = 23, 40, 39, 56


def extend(mask):
    """Add the pandaren bits wherever their source race is entitled. None = no change."""
    if mask <= 0 or mask >= (1 << 31):
        return None
    out = mask
    if mask & BIT_NIGHTELF:
        out |= RACE_A
    if mask & BIT_TROLL:
        out |= RACE_H
    return out if out != mask else None


def sql_extend(col):
    """The same rule as extend(), applied to a row already in the table."""
    return (f'`{col}` = `{col}`'
            f' | IF(`{col}` > 0 AND (`{col}` & {BIT_NIGHTELF}) <> 0, {RACE_A}, 0)'
            f' | IF(`{col}` > 0 AND (`{col}` & {BIT_TROLL}) <> 0, {RACE_H}, 0)')


def q(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--dbc', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()

    d = DBC(a.dbc)
    if d.fields != 57:
        raise SystemExit(f'{a.dbc}: expected 57 fields, got {d.fields} -- wrong expansion?')

    cols = NUMERIC + ['Name_Lang_enUS', 'Name_Lang_Mask',
                      'Description_Lang_enUS', 'Description_Lang_Mask']
    rows, touched = [], []
    for r in d.rows:
        v = list(d.ints(r))
        new = [extend(v[2 + i]) for i in range(4)]
        if not any(x is not None for x in new):
            continue
        for i, nv in enumerate(new):
            if nv is not None:
                v[2 + i] = nv
        touched.append(v[0])

        vals = []
        for idx in range(len(NUMERIC)):
            x = v[idx]
            if idx in FLOATS:
                vals.append('%g' % struct.unpack('<f', struct.pack('<I', x))[0])
            elif idx in SIGNED:
                vals.append(str(x - (1 << 32) if x >= (1 << 31) else x))
            else:
                vals.append(str(x))
        vals += [q(d.s(v[NAME0])), str(v[NFLAGS]), q(d.s(v[DESC0])), str(v[DFLAGS])]
        rows.append('  (' + ', '.join(vals) + ')')
    if not touched:
        sys.exit(f'{a.dbc}: no faction names night elf or troll -- wrong file?')

    with open(a.out, 'w', encoding='utf-8', newline='\n') as f:
        f.write(f"""-- GENERATED by tools/gen-faction-dbc.py -- do not edit by hand.
--
-- {len(touched)} factions where night elf or troll is entitled to base reputation;
-- the pandaren bits are added in the same slot (race 20 follows night elf,
-- race 21 follows troll). Without them ReputationMgr::GetBaseReputation()
-- returns 0 for races 20 and 21, and a pandaren starts Neutral with its own
-- capital.
--
-- Mirroring the source race is deliberate: capitals do not use the "all
-- Alliance" mask but cut their own race out into a separate slot, so an exact
-- match would miss every one of them.
--
-- A DBC override replaces the whole row, so names and descriptions are
-- included. The rows come from an unmodified 3.3.5a Faction.dbc. If your
-- server's Faction.dbc is modified (another race module that ships its own
-- DBC files), regenerate this file from yours, or those changes are lost for
-- the factions listed here.
--
-- A faction already in faction_dbc (another module overrode it and ran
-- first) is not replaced: ON DUPLICATE KEY UPDATE only adds the pandaren bits
-- to the masks it already has. That also makes a rerun a no-op.

INSERT INTO `faction_dbc` (`{'`, `'.join(cols)}`) VALUES
""")
        f.write(',\n'.join(rows) + '\n')
        f.write('ON DUPLICATE KEY UPDATE\n  ' +
                ',\n  '.join(sql_extend(f'ReputationRaceMask_{i}') for i in range(1, 5)) + ';\n')
    print(f'{a.out}: {len(touched)} factions, {len(cols)} columns')


if __name__ == '__main__':
    main()
