#!/usr/bin/env python3
"""Write the server SQL for rows the client patch carries too.

Some DBC rows must be the same on both sides, and they fail separately and in
silence when they are not:

  zz_pandaren_02  CreatureModelData / CreatureDisplayInfo. The server takes
                  collision height and width from the model data.
  zz_pandaren_10  BarberShopStyle. The client offers its own rows and sends the
                  chosen row's ID; the server looks the ID up in ITS table and
                  applies that row's style number. If the two tables number the
                  styles differently, the barber hands out a different haircut
                  than the one chosen.

So these two files are generated from client/rows/, the rows the client patch
is built from, instead of being kept in step by hand.

    gen-shared-sql.py --rows client/rows --out data/sql/db-world
"""
import argparse
import csv
import os
import struct

CMD_COLS = ['ID', 'Flags', 'ModelName', 'SizeClass', 'ModelScale', 'BloodID',
            'FootprintTextureID', 'FootprintTextureLength', 'FootprintTextureWidth',
            'FootprintParticleScale', 'FoleyMaterialID', 'FootstepShakeSize',
            'DeathThudShakeSize', 'SoundID', 'CollisionWidth', 'CollisionHeight',
            'MountHeight', 'GeoBoxMinX', 'GeoBoxMinY', 'GeoBoxMinZ', 'GeoBoxMaxX',
            'GeoBoxMaxY', 'GeoBoxMaxZ', 'WorldEffectScale', 'AttachedEffectScale',
            'MissileCollisionRadius', 'MissileCollisionPush', 'MissileCollisionRaise']
CMD_FLOATS = {4, 7, 8, 9} | set(range(14, 28))
CMD_STRINGS = {2}

CDI_COLS = ['ID', 'ModelID', 'SoundID', 'ExtendedDisplayInfoID', 'CreatureModelScale',
            'CreatureModelAlpha', 'TextureVariation_1', 'TextureVariation_2',
            'TextureVariation_3', 'PortraitTextureName', 'BloodLevel', 'BloodID',
            'NPCSoundID', 'ParticleColorID', 'CreatureGeosetData', 'ObjectEffectPackageID']
CDI_FLOATS = {4}
CDI_STRINGS = {6, 7, 8, 9}

LOCALES = ('enUS', 'enGB', 'koKR', 'frFR', 'deDE', 'enCN', 'zhCN', 'enTW', 'zhTW',
           'esES', 'esMX', 'ruRU', 'ptPT', 'ptBR', 'itIT', 'Unk')
BSS_COLS = (['ID', 'Type'] + [f'DisplayName_Lang_{x}' for x in LOCALES] + ['DisplayName_Lang_Mask'] +
            [f'Description_Lang_{x}' for x in LOCALES] + ['Description_Lang_Mask'] +
            ['Cost_Modifier', 'Race', 'Sex', 'Data'])
BSS_FLOATS = {36}
BSS_STRINGS = set(range(2, 18)) | set(range(19, 35))


def rows(path):
    with open(path, newline='', encoding='utf-8') as f:
        rd = csv.reader(f)
        next(rd)
        return list(rd)


def lit(i, x, floats, strings):
    if i in strings:
        return "'" + x.replace('\\', '\\\\').replace("'", "\\'") + "'"
    v = int(x)
    if i in floats:
        return '%.9g' % struct.unpack('<f', struct.pack('<I', v))[0]
    return str(v - (1 << 32) if v >= (1 << 31) else v)


def values(rs, floats, strings):
    return ',\n'.join('  (' + ', '.join(lit(i, x, floats, strings) for i, x in enumerate(r)) + ')'
                      for r in rs)


def models(rowsdir, out):
    cmd = rows(os.path.join(rowsdir, 'CreatureModelData.csv'))
    cdi = rows(os.path.join(rowsdir, 'CreatureDisplayInfo.csv'))
    ids_m = ', '.join(r[0] for r in cmd)
    ids_d = ', '.join(r[0] for r in cdi)
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write(f"""-- GENERATED by tools/gen-shared-sql.py from client/rows/ -- do not edit by hand.
--
-- Pandaren model and display rows, the same as the client patch's.
--
-- Pandaren do not exist in 3.3.5 at all, so both model and display are created
-- here. A free ID must be free in the DBC file AND in the override table:
-- CreatureModelData's IDs are sparse up to 7050 (3700 and 3701 are unused
-- gaps), CreatureDisplayInfo ends at 36446. DBCDatabaseLoader::Load fills gaps
-- and extends the index alike.
--
-- The file name must end in .mdx, not .m2: the client maps .mdx to .m2 on
-- lookup, and every existing race is written that way.
--
-- The collision box is read off the model's own collision box, the way the
-- stock races' rows agree with their models. A wrong CollisionHeight shows as
-- a character sunk into or floating above the ground, a wrong MountHeight as
-- a rider beside the mount.
--
-- ExtendedDisplayInfoID 0 is right for a PLAYER display: the texture is
-- composed from the player's own skin and hair. An NPC would need a baked
-- CreatureDisplayInfoExtra row, or it stands untextured.

DELETE FROM `creaturemodeldata_dbc` WHERE `ID` IN ({ids_m});
DELETE FROM `creaturedisplayinfo_dbc` WHERE `ID` IN ({ids_d});

INSERT INTO `creaturemodeldata_dbc` (`{'`, `'.join(CMD_COLS)}`) VALUES
{values(cmd, CMD_FLOATS, CMD_STRINGS)};

INSERT INTO `creaturedisplayinfo_dbc` (`{'`, `'.join(CDI_COLS)}`) VALUES
{values(cdi, CDI_FLOATS, CDI_STRINGS)};
""")
    print(f'{out}: {len(cmd)} models, {len(cdi)} displays')


def barbershop(rowsdir, out):
    bss = rows(os.path.join(rowsdir, 'BarberShopStyle.csv'))
    lo, hi = min(int(r[0]) for r in bss), max(int(r[0]) for r in bss)
    count = {}
    for r in bss:
        k = (int(r[37]), int(r[38]), int(r[1]))
        count[k] = count.get(k, 0) + 1
    summary = '\n'.join(f'--   race {k[0]} {"male" if k[1] == 0 else "female"} '
                        f'{"hair" if k[2] == 0 else "facial hair"}: {n}'
                        for k, n in sorted(count.items()))
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write(f"""-- GENERATED by tools/gen-shared-sql.py from client/rows/ -- do not edit by hand.
--
-- Barber chairs for races 20 and 21. Without them a pandaren can never change
-- hairstyle after character creation: `HandleAlterAppearance` requires
-- `bs->race == getRace()`, so the server rejects any choice not listed here.
--
-- These are the client patch's rows, ID for ID. The client sends the chosen
-- row's ID and the server applies the style number (Data) from its own row,
-- so the two tables must agree on both.
--
-- The rows are MoP's own with the race rewritten, so the names are
-- Blizzard's. The female hairstyles are the ten the model still has geosets
-- for, renumbered 0-9; the rows keep their IDs.
--
-- Type 3 is left out: in MoP it is skin colour, in WotLK it is tauren horns.
--
{summary}

DELETE FROM `barbershopstyle_dbc` WHERE `ID` BETWEEN {lo} AND {hi};

INSERT INTO `barbershopstyle_dbc` (`{'`, `'.join(BSS_COLS)}`) VALUES
{values(bss, BSS_FLOATS, BSS_STRINGS)};

-- Check:
--   SELECT Race, Sex, Type, COUNT(*) FROM barbershopstyle_dbc
--    WHERE Race IN (20, 21) GROUP BY 1, 2, 3;
-- And in game: visit a barber as a pandaren of each sex, pick a style and
-- check that the one you get is the one you picked.
""")
    print(f'{out}: {len(bss)} barber styles, IDs {lo}-{hi}')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--rows', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()
    models(a.rows, os.path.join(a.out, 'zz_pandaren_02-models.sql'))
    barbershop(a.rows, os.path.join(a.out, 'zz_pandaren_10-barbershop.sql'))


if __name__ == '__main__':
    main()
